### ISSUE TITLE
ClassCastException is thrown when the key algorithm of signature and certification key is different

### ISSUE THREAD

**Issue by p-barabas** [vanitasvitae/pgpainless#266]
I have a PGP public key which has two userId certification signatures: one if the self certification and another is a signature "signed" with a trusted key. The public key is an ECC key, self certification is made with EdDSA, the other signature is made with RSA.
When signature verification logic runs, the SignatureVerification's correctSignatureOverUserId method throws a ClassCastException which means Ed25519PublicKeyParams cannot be case to RSAPublicKeyParams.
It is thrown in signature.init(...). I think the preferred solution would be to catch this type of exception also and throw SignatureValidationException instead like in case of PGPException.

**Comment by vanitasvitae** [comment]
What version of PGPainless are you using? This bug sounds a lot like one that was fixed in PGPainless 1.1.2 (with [this commit](https://github.com/pgpainless/pgpainless/commit/f1f7dec8b6b5cae50c8ffea596418e241fe709ab)).

**Comment by p-barabas** [comment]
In latest (1.1.4) seems it exists. Mentioned commit is about revocation signature. It is different.

**Comment by vanitasvitae** [comment]
Could you post a stacktrace of this happening (without your changes)?

**Comment by p-barabas** [comment]
java.lang.ClassCastException: org.bouncycastle.crypto.params.Ed25519PublicKeyParameters cannot be cast to org.bouncycastle.crypto.params.RSAKeyParameters
	at org.bouncycastle.crypto.engines.RSACoreEngine.init(Unknown Source:10)
	at org.bouncycastle.crypto.engines.RSABlindedEngine.init(Unknown Source:2)
	at org.bouncycastle.crypto.encodings.PKCS1Encoding.init(Unknown Source:39)
	at org.bouncycastle.crypto.signers.RSADigestSigner.init(Unknown Source:59)
	at org.bouncycastle.openpgp.operator.bc.BcPGPContentVerifierBuilderProvider$BcPGPContentVerifierBuilder.build(Unknown Source:19)
	at org.bouncycastle.openpgp.PGPSignature.init(Unknown Source:16)
	at org.pgpainless.signature.consumer.SignatureValidator$19.verify(SignatureValidator.java:575)
	at org.pgpainless.signature.consumer.SignatureVerifier.verifyUserIdCertification(SignatureVerifier.java:95)
	at org.pgpainless.signature.consumer.SignatureVerifier.verifySignatureOverUserId(SignatureVerifier.java:52)
	at org.pgpainless.signature.consumer.SignatureVerifier.verifySignatureOverUserId(SignatureVerifier.java:457)
	at org.pgpainless.signature.consumer.CertificateValidator.validateCertificate(CertificateValidator.java:116)
	at org.pgpainless.signature.consumer.CertificateValidator.validateCertificateAndVerifyOnePassSignature(CertificateValidator.java:274)
	at org.pgpainless.decryption_verification.SignatureInputStream$VerifySignatures.verifyOnePassSignatures(SignatureInputStream.java:156)
	at org.pgpainless.decryption_verification.SignatureInputStream$VerifySignatures.read(SignatureInputStream.java:87)
	at org.pgpainless.decryption_verification.DecryptionStream.read(DecryptionStream.java:61)
	at org.bouncycastle.util.io.Streams.pipeAll(Unknown Source:3)
	at org.bouncycastle.util.io.Streams.pipeAll(Unknown Source:2)
	at com.example.services.OpenPGPServiceImpl.verifyAndDecrypt(OpenPGPService.kt:209)
	at com.example.workers.EmailsWorkerImpl.fetchAndDecryptEmail(EmailsWorkerImpl.kt:849)
	at com.example.workers.EmailsWorkerImpl.access$fetchAndDecryptEmail(EmailsWorkerImpl.kt:34)
	at com.example.workers.EmailsWorkerImpl$fetchAndDecryptEmail$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by vanitasvitae** [comment]
Thanks for the bug report and the fix!

**Comment by vanitasvitae** [comment]
I released version 1.1.5 which contains the fix. It should be available from maven central in a few hours.

**Comment by p-barabas** [comment]
Thanks.
