### ISSUE TITLE
NullPointerException when verifying against an OpenPGP certificate with a direct key sig without feature flags

### ISSUE THREAD

**Issue by dkg** [vanitasvitae/pgpainless#332]
I've tried using `pgpainless-cli verify sig cert < msg` where `cert` contains a single OpenPGP v4 certificate with a Direct Key Signature packet attached to the primary key, and that direct key signature packet has no "key usage" feature flags.

`sig` is made by the primary key itself, and the primary key has UID self-signatures that *do* have key feature flags set that include the `signing-capable` bit.

When i do this, `pgpainless-cli` crashes with the following backtrace.

```
java.lang.NullPointerException
	at org.pgpainless.signature.consumer.CertificateValidator.validateCertificate(CertificateValidator.java:174)
	at org.pgpainless.signature.consumer.CertificateValidator.validateCertificateAndVerifyInitializedSignature(CertificateValidator.java:273)
	at org.pgpainless.decryption_verification.SignatureInputStream$VerifySignatures.verifyDetachedSignatures(SignatureInputStream.java:177)
	at org.pgpainless.decryption_verification.SignatureInputStream$VerifySignatures.finalizeSignatures(SignatureInputStream.java:96)
	at org.pgpainless.decryption_verification.SignatureInputStream$VerifySignatures.read(SignatureInputStream.java:85)
	at org.pgpainless.decryption_verification.DecryptionStream.read(DecryptionStream.java:61)
	at org.bouncycastle.util.io.Streams.drain(Unknown Source)
	at org.pgpainless.sop.DetachedVerifyImpl.data(DetachedVerifyImpl.java:71)
	at sop.cli.picocli.commands.VerifyCmd.run(VerifyCmd.java:87)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at sop.cli.picocli.SopCLI.execute(SopCLI.java:84)
	at org.pgpainless.cli.PGPainlessCLI.execute(PGPainlessCLI.java:29)
	at org.pgpainless.cli.PGPainlessCLI.main(PGPainlessCLI.java:22)
```

## version info

```
C$ pgpainless-cli version --extended
PGPainless-SOP 1.3.7
https://codeberg.org/PGPainless/pgpainless/src/branch/master/pgpainless-sop

Implementation of the Stateless OpenPGP Protocol Version 04
https://datatracker.ietf.org/doc/html/draft-dkg-openpgp-stateless-cli-04

Based on pgpainless-core 1.3.7
https://pgpainless.org

Using Bouncy Castle 1.71
https://www.bouncycastle.org/java.html
```

**Comment by dkg** [comment]
The direct key signature packet just contains a [Revocation Key](https://datatracker.ietf.org/doc/html/rfc4880#section-5.2.3.15) subpacket, so i think this kind of certificate is pretty easy to generate with existing tooling.

And, indeed, if i strip out that direct key signature packet from the certificate, the verification succeeds.

**Comment by vanitasvitae** [comment]
Could you check out the code from [this PR](https://github.com/pgpainless/pgpainless/pull/333) and see if it fixes the issue?

To build pgpainless-cli, you can do
```
./gradlew installDist
```

After that you can navigate to `pgpainless-cli/build/install/pgpainless-cli/bin/` where you will find a `pgpainless-cli` script which should behave like the debian package.
With that you should be able to test your artefacts (simply with `./pgpainless-cli` instead of `pgpainless-cli`).

**Comment by dkg** [comment]
I can't rebuild pgpainless right now, sorry, i don't have that build env set up and fetching and executing that much code isn't going to happen right away.  A bit more digging points me to a certificate like DB546519B22089EFDBE8130940DC6189F9269749 which has this property.  I suspect your inbox has a message signed by that certificate if you want to try to replicate it locally!

**Comment by vanitasvitae** [comment]
No worries :)
Again, thank you very much for the report!
