### ISSUE TITLE
`pgpainless-cli verify` fails with `Subkey is not bound`

### ISSUE THREAD

**Issue by dkg** [vanitasvitae/pgpainless#334]
I'm trying to verify a signature made by a subkey  of 8F17777118A33DDA9BA48E62AACB3243630052D9, and i'm seeing this warning:

```
[main] WARN org.pgpainless.decryption_verification.SignatureInputStream$VerifySignatures - One-pass-signature verification failed for signature made by key C03FA6411B03AE12576461187223B56678E02528 8F17777118A33DDA9BA48E62AACB3243630052D9: Subkey is not bound.: 1 rejected signatures:
SUBKEY_BINDING Fri Sep 30 20:00:23 EDT 2022: Cannot process list of embedded signatures.
```

`sqop` and `sopgpy` and `gosop` and `rnp-sop` and `gpgme-sop` all seem to think that the subkey is properly bound.

## version info

(still running the version in debian unstable, sorry i haven't had a chance to test it against the latest version yet)

```
PGPainless-SOP 1.3.7
https://codeberg.org/PGPainless/pgpainless/src/branch/master/pgpainless-sop

Implementation of the Stateless OpenPGP Protocol Version 04
https://datatracker.ietf.org/doc/html/draft-dkg-openpgp-stateless-cli-04

Based on pgpainless-core 1.3.7
https://pgpainless.org

Using Bouncy Castle 1.71
https://www.bouncycastle.org/java.html
```

**Comment by vanitasvitae** [comment]
Could you (if possible) include a bit more of the stacktrace? Alternatively, could you point me to where I can find that particular signature? I suspect it to be an artefact from the KOO bootstrapping process?

**Comment by vanitasvitae** [comment]
I identified an artefact made by the key and manually transformed it to a detached-verifiable message by cutting away MIME stuff.

However, on 1.3.7, I can successfully verify that artefact.
```
$ ./pgpainless-cli verify mail.sig key.pub < mail             
2022-10-25T06:44:37Z C03FA6411B03AE12576461187223B56678E02528 8F17777118A33DDA9BA48E62AACB3243630052D9
```

**Comment by dkg** [comment]
yes, that's what it's from.

Here are the files:
- [msg.eml.sig.txt](https://github.com/pgpainless/pgpainless/files/9961027/msg.eml.sig.txt)
- [msg.eml.txt](https://github.com/pgpainless/pgpainless/files/9961028/msg.eml.txt)
- [signer.cert.txt](https://github.com/pgpainless/pgpainless/files/9961029/signer.cert.txt)

here's the full backtrace:

```
$ pgpainless-cli verify msg.eml.sig.txt signer.cert.txt < msg.eml.txt 
[main] WARN org.pgpainless.decryption_verification.SignatureInputStream$VerifySignatures - One-pass-signature verification failed for signature made by key C03FA6411B03AE12576461187223B56678E02528 8F17777118A33DDA9BA48E62AACB3243630052D9: Subkey is not bound.: 1 rejected signatures:
SUBKEY_BINDING Fri Sep 30 20:00:23 EDT 2022: Cannot process list of embedded signatures.

org.pgpainless.exception.SignatureValidationException: Subkey is not bound.: 1 rejected signatures:
SUBKEY_BINDING Fri Sep 30 20:00:23 EDT 2022: Cannot process list of embedded signatures.

	at org.pgpainless.signature.consumer.CertificateValidator.validateCertificate(CertificateValidator.java:213)
	at org.pgpainless.signature.consumer.CertificateValidator.validateCertificateAndVerifyInitializedSignature(CertificateValidator.java:273)
	at org.pgpainless.decryption_verification.SignatureInputStream$VerifySignatures.verifyDetachedSignatures(SignatureInputStream.java:177)
	at org.pgpainless.decryption_verification.SignatureInputStream$VerifySignatures.finalizeSignatures(SignatureInputStream.java:96)
	at org.pgpainless.decryption_verification.SignatureInputStream$VerifySignatures.read(SignatureInputStream.java:85)
	at org.pgpainless.decryption_verification.DecryptionStream.read(DecryptionStream.java:61)
	at org.bouncycastle.util.io.Streams.drain(Unknown Source)
	at org.pgpainless.sop.DetachedVerifyImpl.data(DetachedVerifyImpl.java:71)
	at sop.cli.picocli.commands.VerifyCmd.run(VerifyCmd.java:87)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at sop.cli.picocli.SopCLI.execute(SopCLI.java:84)
	at org.pgpainless.cli.PGPainlessCLI.execute(PGPainlessCLI.java:29)
	at org.pgpainless.cli.PGPainlessCLI.main(PGPainlessCLI.java:22)
No verifiable signature found.
sop.exception.SOPGPException$NoSignature: No verifiable signature found.
	at sop.cli.picocli.commands.VerifyCmd.run(VerifyCmd.java:90)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at sop.cli.picocli.SopCLI.execute(SopCLI.java:84)
	at org.pgpainless.cli.PGPainlessCLI.execute(PGPainlessCLI.java:29)
	at org.pgpainless.cli.PGPainlessCLI.main(PGPainlessCLI.java:22)
Caused by: sop.exception.SOPGPException$NoSignature: No verifiable signature found.
	at org.pgpainless.sop.DetachedVerifyImpl.data(DetachedVerifyImpl.java:83)
	at sop.cli.picocli.commands.VerifyCmd.run(VerifyCmd.java:87)
	... 11 more
3 $
```

**Comment by dkg** [comment]
looks to me like the issue is with the form of the certificate, not the data.

fwiw, [signer.cert.txt](https://github.com/pgpainless/pgpainless/files/9961029/signer.cert.txt) was produced by using `gpg --export-options export-minimal --armor export` -- maybe that means `gpg` is doing a dangerous minimization during export?  Even if that's the case, there are two possible scenarios here:

- pgpainless-cli is doing an erroneous verification step
- pgpainless-cli is doing a good check, and all the other SOP implementations that succeed in verification need to improve

**Comment by vanitasvitae** [comment]
Interesting. If I perform the same check using the full cert, it works. I will investigate.

**Comment by vanitasvitae** [comment]
```
Caused by: org.pgpainless.exception.SignatureValidationException: Missing primary key binding signature on signing capable subkey 7223b56678e02528: 1 rejected signatures:
PRIMARYKEY_BINDING Tue Apr 07 11:42:46 CEST 2015: Signature was created before the signing key was bound to the key ring.
```
I guess, PGPainless ran into a hen and egg problem and chose the wrong strategy to resolve it :D

**Comment by vanitasvitae** [comment]
With the full cert thats not an issue, since there is an older binding signature from when the key was created. The minimized cert only contains the most recent binding signature, so when checking whether the backsig was created before the key was bound, PGPainless rejects the binding signature.
This will be tricky to fix :/

**Comment by dkg** [comment]
I think the argument is that the backsig can be created any time that the subkey itself is valid.  that is, within the union of the two time ranges:  [subkey creation, subkey revocation/expiration] and [primary creation, primary revocation/expiration].

So I think that the window of reasonable times to make a backsig should be the same window as the reasonable times to make the binding signature itself.

**Comment by dkg** [comment]
On IRC, i observed this scenario that would be broken by the temporal ordering rules i think pgpainless is using to validate backsigs:

i can imagine an additional-signing-device registration procedure where the additional signing device sends the primary signing device its signing-capable subkey with a backsig, and the primary signing device creates a binding signature this shouldn't have to happen synchronously, and we don't want either device to have to lie about the system time to make it work.

**Comment by vanitasvitae** [comment]
Quote @dkg:
> vanitasvitae: the way i see it, the backsig is the one signature that a subkey makes that is *independent* of the authority of the primary key.  That is, the goal of the backsig is to clarify that the owner of the secret key *intends* it to be a subkey to a particular primary key.
> so, it can't make that signature before it is created; and such an assertion after the primary's binding signature has expired or been revoked is meaningless.  and it is also meaningless to make it on the primary key before the primary key's own creation time, or after the primary key itself has expired or been revoked (who cares about a subkey in those cases anyway?)

I will see if I can change the validation logic for backsigs, such that instead of checking whether the key is bound, it only checks whether the sig was made within the intersection of the subkeys lifetime and the primary keys lifetime.
