### ISSUE TITLE
Support for OpenPGP V6 keys

### ISSUE THREAD

**Issue by vanitasvitae** [vanitasvitae/pgpainless#343]
Bouncy Castle currently does not yet support OpenPGP V5 keys.
(I added [V5OpenPgpKeyTest](https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/test/java/org/pgpainless/key/V5OpenPgpKeyTest.java) to confirm this).

This doesn't come as a surprise of course, since the standardization efforts aren't even finished yet.
However, we could think about how to work towards future support already.

From the stacktrace given by the test I suppose that algorithm support in BCs ECPublicBCPGKey class is needed:
```
future extensions not yet implemented
java.io.IOException: future extensions not yet implemented
	at org.bouncycastle.bcpg.ECPublicBCPGKey.readBytesOfEncodedLength(Unknown Source)
	at org.bouncycastle.bcpg.ECPublicBCPGKey.<init>(Unknown Source)
	at org.bouncycastle.bcpg.EdDSAPublicBCPGKey.<init>(Unknown Source)
	at org.bouncycastle.bcpg.PublicKeyPacket.<init>(Unknown Source)
	at org.bouncycastle.bcpg.BCPGInputStream.readPacket(Unknown Source)
	at org.bouncycastle.openpgp.PGPPublicKeyRing.readPublicKeyPacket(Unknown Source)
	at org.bouncycastle.openpgp.PGPPublicKeyRing.<init>(Unknown Source)
	at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
	at org.pgpainless.key.parsing.KeyRingReader.readPublicKeyRing(KeyRingReader.java:224)
	at org.pgpainless.key.parsing.KeyRingReader.readPublicKeyRing(KeyRingReader.java:203)
	at org.pgpainless.key.parsing.KeyRingReader.publicKeyRing(KeyRingReader.java:77)
	at org.pgpainless.key.parsing.KeyRingReader.publicKeyRing(KeyRingReader.java:82)
	at org.pgpainless.key.parsing.KeyRingReader.publicKeyRing(KeyRingReader.java:87)
	at org.pgpainless.key.V5OpenPgpKeyTest.testParseCert(V5OpenPgpKeyTest.java:53)
[...]
```

I think this indicates that the class cannot yet parse keys with lenght encoding bytes where the first byte is a zero?
Related [BouncyCastle source](https://github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/bcpg/ECPublicBCPGKey.java#L110-L113) that throws.
Related [certificate dump](https://dump.sequoia-pgp.org/?data=-----BEGIN%20PGP%20PUBLIC%20KEY%20BLOCK-----%0D%0A%0D%0AxjcFY4d/4xYAAAAtCSsGAQQB2kcPAQEHQPlNp7tI1gph5WdwamWH0DMZmbud%0D%0AiRoIJC6thFQ9%2BJWjwqQFHxYKAAAAHwUCY4d/4wMLCQcFFQoOCAwCFgACGwMC%0D%0AHgkFJwkCBwIAAAAjIiEFF7z4Nm2UNvevN%2BraFWxklGVuWpdpzy1cs0X4uDQ2%0D%0A9lJ5xSazswKsjQ5%2BnWIpXpDAYUQBAOd3furFHev97PBcR9ZR3rg0qwfLzyjd%0D%0AQbdBqyuBH15LAQCYI8kezQu%2BhTzUgWxiERhpmiT24LQOF2c7aXBhRsJMBc48%0D%0ABWOHf%2BMSAAAAMgorBgEEAZdVAQUBAQdA/Pf8KarOAUj0Pq2/Og%2BWkdCjIqJD%0D%0AYlYngO2SXahOcVsDAQgHwo4FGBYKAAAACQUCY4d/4wIbDAAAACMiIQUXvPg2%0D%0AbZQ296836toVbGSUZW5al2nPLVyzRfi4NDb2Uu/EunWWplIOSvrF31Pzdbps%0D%0AEwD/SYz1a7Zx47b2E2s2ZnWYQJ/GkS1LRhtaMLZixsAkoesA/2za1huJx31Z%0D%0AP2hBxmeHI2hZWqRa%2BbdUEqbC%2B5xMveIL%0D%0A%3DsVUI%0D%0A-----END%20PGP%20PUBLIC%20KEY%20BLOCK-----&hex=on).

What makes me wonder a bit is, that apparently the length byte that if I manually count the bytes, I end up at a byte with value `0x16`, which should not trigger the exception. Maybe I am doing something wrong, or the key is malformed after all.

We will see...

**Comment by dkg** [comment]
just wanted to note that due to the upcoming release of the crypto-refresh draft, this (and the milestone) should probably be update to refer to v6, not v5.

**Comment by vanitasvitae** [comment]
Yeah, you are right!

**Comment by vanitasvitae** [comment]
WIP: https://github.com/bcgit/bc-java/pull/1353

**Comment by vanitasvitae** [comment]
Some support for this was merged with https://github.com/bcgit/bc-java/pull/1411 and https://github.com/bcgit/bc-java/pull/1413

The new algorithms (X25519, X448, Ed25519, Ed448) cannot yet be used productively though.

**Comment by dkg** [comment]
Thanks for working on this!  Note that v6 key, signature, and OPS support should be possible independently of the new pubkey algorithm types.  Would it make sense to have a separate issue to track the native EdDSA and CFRG X* pubkey algorithms?  I see #263 about Ed448 and X448, but i don't see it for the *25519 variants.

**Comment by dkg** [comment]
ping here on the status v6 key, signature, and OPS support, independently of the new pubkey algorithms.

**Comment by vanitasvitae** [comment]
There is still v6-related work ongoing on the Bouncy Castle side, so until that is finished, it does not make much sense for me to work on v6 support in PGPainless.

**Comment by vanitasvitae** [comment]
Fixed with #468

**Comment by vanitasvitae** [comment]
This is now implemented in PGPainless 2.0.0 :)
