### ISSUE TITLE
Unable to encrypt data with GPG 2.0.22 public key : Key XXX does not have a valid/acceptable signature to derive an expiration date from.

### ISSUE THREAD

**Issue by farnulfo** [vanitasvitae/pgpainless#398]
Hi,

When I try to encrypt data for a public key generated from GnuPG 2.0.22 (current version of gpg on RedHat 7.9), I've the following exception:

pgpainless-core:1.6.0, pgpainless-sop:1.6.0

```
Exception in thread "main" org.pgpainless.exception.KeyException$UnacceptableSelfSignatureException: Key 24E8E567BF46EA8955EB30571C7429B041B68CA7 does not have a valid/acceptable signature to derive an expiration date from.
	at org.pgpainless.encryption_signing.EncryptionOptions.addAsRecipient(EncryptionOptions.java:246)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:211)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:199)
	at org.pgpainless.encryption_signing.EncryptionOptions.addRecipients(EncryptionOptions.java:127)
	at org.pgpainless.sop.EncryptImpl.withCert(EncryptImpl.java:109)
	at sop.operation.Encrypt.withCert(Encrypt.java:147)
	at com.example.pgp.EncryptWithSOP.main(EncryptWithSOP.java:32)
```

Code :

```
package com.example.pgp;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import org.bouncycastle.openpgp.PGPException;
import org.pgpainless.exception.KeyException;
import org.pgpainless.sop.SOPImpl;
import sop.SOP;

public class EncryptWithSOP {

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     * @throws org.bouncycastle.openpgp.PGPException
     */
    public static void main(String[] args) throws IOException, KeyException, PGPException {
        // Instantiate the API
        SOP sop = new SOPImpl();
        System.out.println(sop.listProfiles().encrypt());

        String publicKeyGPG = Files.readString(Path.of("test-gpg-2-0-22.gpg"));

        byte[] publicKey = sop.dearmor().data(publicKeyGPG.getBytes()).getBytes();

        byte[] plaintext = "Hello, World!\n".getBytes(); // plaintext

        byte[] ciphertext = sop.encrypt()
                // encrypt for each recipient
                .withCert(publicKey)
                .plaintext(plaintext)
                .getBytes();
        System.out.println("ciphertext:");
        System.out.println(ciphertext);
        System.out.println(String.valueOf(ciphertext));

        // wrap data in ASCII armor
        byte[] armoredData = sop.armor()
                .data(ciphertext)
                .getBytes();
        System.out.println("data:\n" + new String(armoredData,"UTF-8"));
        

    }

}
```

I've no problem with a public key generated from GPG 2.2.20.

Is there a way to make it work with GPG 2.0.22 ?

The public key generated by GPP 2.0.22 :
[test-gpg-2-0-22.gpg.txt](https://github.com/pgpainless/pgpainless/files/12070630/test-gpg-2-0-22.gpg.txt)

**Comment by vanitasvitae** [comment]
The key you included in the report uses SHA-1 as signature hash algorithm. The use of SHA-1 has been deprecated for a while and since february of this year, PGPainless rejects signatures made using SHA-1 as invalid, which invalidates the key in this case.

The SHA-1 signature is probably placed on the key because of a misconfigured GnuPG installation that still has SHA-1 set as preferable hash algorithm.

If you want to accept keys with SHA-1 signatures, you can modify PGPainless' algorithm policy: 
https://pgpainless.readthedocs.io/en/latest/quickstart.html#weak-keys-and-broken-algorithms
https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/test/java/org/pgpainless/example/ManagePolicy.java#L91

**Comment by farnulfo** [comment]
Hi @vanitasvitae thanks for your answer !

I'll put some details for other that might have the same problem.

I used online version of pgpdump to see all the details of the public key
https://www.lirnberger.com/tools/pgpdump/ : 

```
pgpdump <ASCII data>

Old: Public Key Packet(tag 6)(525 bytes)
	Ver 4 - new
	Public key creation time - Mon Jul 17 16:13:01 CEST 2023
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA n(4096 bits) - ...
	RSA e(17 bits) - ...
Old: User ID Packet(tag 13)(49 bytes)
	User ID - TestGPG (test with GPG 2.0.22) <test@example.com>
Old: Signature Packet(tag 2)(575 bytes)
	Ver 4 - new
	Sig type - Positive certification of a User ID and Public Key packet(0x13).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA1(hash 2)
[...]
```

"Hash alg - SHA1(hash 2)" : confirm that GPG 2.0.X default conf use SHA1 as hash algorithm when it create a key.

According to 
https://pgpainless.readthedocs.io/en/latest/quickstart.html#weak-keys-and-broken-algorithms
https://github.com/pgpainless/pgpainless/blob/main/pgpainless-core/src/test/java/org/pgpainless/example/ManagePolicy.java#L91

I changed my program by setting a new CustomSignatureHashPolicy that accept SHA1 and it worked:
```
package com.example.pgp;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import org.bouncycastle.openpgp.PGPException;
import org.pgpainless.PGPainless;
import org.pgpainless.algorithm.HashAlgorithm;
import org.pgpainless.exception.KeyException;
import org.pgpainless.policy.Policy;
import org.pgpainless.sop.SOPImpl;
import sop.SOP;

public class EncryptWithSOPAndCustomPolicyWithoutSigning {

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     * @throws org.bouncycastle.openpgp.PGPException
     */
    public static void main(String[] args) throws IOException, KeyException, PGPException {

        setCustomSignatureHashPolicy();

        // Instantiate the API
        SOP sop = new SOPImpl();
        System.out.println(sop.listProfiles().encrypt());

        String publicKeyGPG = Files.readString(Path.of("test-gpg-2-0-22.gpg"));

        byte[] publicKey = sop.dearmor().data(publicKeyGPG.getBytes()).getBytes();

        byte[] plaintext = "Hello, World from java!\n".getBytes(); // plaintext
        

        byte[] ciphertext = sop.encrypt()
                // encrypt for each recipient
                .withCert(publicKey)
                .plaintext(plaintext)
                .getBytes();
        System.out.println("ciphertext:");
        System.out.println(ciphertext);
        System.out.println(String.valueOf(ciphertext));

        // wrap data in ASCII armor
        byte[] armoredData = sop.armor()
                .data(ciphertext)
                .getBytes();
        System.out.println("data:\n" + new String(armoredData, "UTF-8"));

    }

    public static void setCustomSignatureHashPolicy() {
        // Get PGPainless' policy singleton
        Policy policy = PGPainless.getPolicy();

        // Create a new custom policy which contains SHA-1
        Policy.HashAlgorithmPolicy customPolicy = new Policy.HashAlgorithmPolicy(
                // The default hash algorithm will be used when hash algorithm negotiation fails when creating a sig
                HashAlgorithm.SHA512,
                // List of acceptable hash algorithms
                Arrays.asList(HashAlgorithm.SHA512, HashAlgorithm.SHA384, HashAlgorithm.SHA256, HashAlgorithm.SHA224, HashAlgorithm.SHA1));
        // Set the hash algo policy as policy for non-revocation signatures
        policy.setSignatureHashAlgorithmPolicy(customPolicy);
    }

}

```
