### ISSUE TITLE
Not thread safe when adding recipient keys

### ISSUE THREAD

**Issue by eitch** [vanitasvitae/pgpainless#443]
**Describe the bug**
I have code which asynchronously sends encrypted mails on startup of my application, e.g. for each migration executed.

When only one encrypted mail is sent, then all works well. Adding locking solves the issue as well.

In some cases multiple emails were sent, resulting in multiple asynchronous encryption calls. This fails with the following stack trace:

	java.lang.IllegalStateException: Failed to prepare message for sending!
		at li.strolch.utils.SmtpMailer.sendEncryptedEmail(SmtpMailer.java:296)
		at li.strolch.handler.mail.SmtpMailHandler.sendEncryptedMail(SmtpMailHandler.java:140)
		at li.strolch.handler.mail.SmtpMailHandler.doSendEncryptedMail(SmtpMailHandler.java:229)
		at li.strolch.handler.mail.SmtpMailHandler.lambda$sendEncryptedMailAsync$0(SmtpMailHandler.java:190)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
		at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
		at java.base/java.lang.Thread.run(Thread.java:1570)
	Caused by: java.lang.IllegalStateException: Failed to encrypt and sign plain text!
		at li.strolch.utils.SmtpMailer.signAndEncrypt(SmtpMailer.java:457)
		at li.strolch.utils.SmtpMailer.sendEncryptedEmail(SmtpMailer.java:294)
		... 9 common frames omitted
	Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 4
		at org.bouncycastle.crypto.digests.GeneralDigest.update(Unknown Source)
		at org.bouncycastle.crypto.signers.RSADigestSigner.update(Unknown Source)
		at org.bouncycastle.openpgp.operator.bc.SignerOutputStream.write(Unknown Source)
		at org.bouncycastle.openpgp.PGPDefaultSignatureGenerator.byteUpdate(Unknown Source)
		at org.bouncycastle.openpgp.PGPDefaultSignatureGenerator.update(Unknown Source)
		at org.bouncycastle.openpgp.PGPSignature.update(Unknown Source)
		at org.bouncycastle.openpgp.PGPDefaultSignatureGenerator.updateWithPublicKey(Unknown Source)
		at org.bouncycastle.openpgp.PGPSignature.doVerifyCertification(Unknown Source)
		at org.bouncycastle.openpgp.PGPSignature.verifyCertification(Unknown Source)
		at org.bouncycastle.openpgp.PGPSignature.verifyCertification(Unknown Source)
		at org.pgpainless.signature.consumer.SignatureValidator$19.verify(SignatureValidator.java:619)
		at org.pgpainless.signature.consumer.SignaturePicker.pickLatestUserIdCertificationSignature(SignaturePicker.java:259)
		at org.pgpainless.key.info.KeyRingInfo$Signatures.<init>(KeyRingInfo.java:1293)
		at org.pgpainless.key.info.KeyRingInfo.<init>(KeyRingInfo.java:116)
		at org.pgpainless.key.info.KeyRingInfo.<init>(KeyRingInfo.java:101)
		at org.pgpainless.encryption_signing.EncryptionOptions.addAsRecipient(EncryptionOptions.java:292)
		at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:265)
		at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:253)
		at org.pgpainless.encryption_signing.EncryptionOptions.addRecipients(EncryptionOptions.java:181)
		at li.strolch.utils.SmtpMailer.getEncryptionOptions(SmtpMailer.java:472)
		at li.strolch.utils.SmtpMailer.signAndEncrypt(SmtpMailer.java:446)
		... 10 common frames omitted

**Version**
- `pgpainless-core`: 1.6.7

**To Reproduce**
The following shows my code:
```
	protected String signAndEncrypt(String plainText) {
		try {
//			if (!this.lock.tryLock(10, TimeUnit.SECONDS))
//				throw new IllegalStateException("Failed to acquired lock in 10s!");

			ByteArrayOutputStream signatureResult = new ByteArrayOutputStream();
			EncryptionStream encryptionStream = PGPainless
					.encryptAndOrSign()
					.onOutputStream(signatureResult)
					.withOptions(ProducerOptions
							.signAndEncrypt(getEncryptionOptions(), getSigningOptions())
							.setAsciiArmor(true)
							.setVersion(""));

			Streams.pipeAll(new ByteArrayInputStream(plainText.getBytes()), encryptionStream);
			encryptionStream.close();

			return signatureResult.toString(UTF_8);
//		} catch (InterruptedException e) {
//			throw new IllegalStateException("Interrupted while waiting to lock", e);
		} catch (Exception e) {
			throw new IllegalStateException("Failed to encrypt and sign plain text!", e);
//		} finally {
//			this.lock.unlock();
		}
	}

	protected SigningOptions getSigningOptions() throws PGPException {
		return new SigningOptions()
				.addInlineSignature(SecretKeyRingProtector.unlockAnyKeyWith(new Passphrase(this.signingKeyPassword)),
						this.signingKeyRing, DocumentSignatureType.BINARY_DOCUMENT)
				.overrideHashAlgorithm(HashAlgorithm.SHA256);
	}

	protected EncryptionOptions getEncryptionOptions() {
		return new EncryptionOptions()
				.addRecipients(this.recipientKeyRings)
				.overrideEncryptionAlgorithm(SymmetricKeyAlgorithm.AES_256);
	}
```

**Expected behavior**
Encryption/Signing should be thread safe, when using new EncryptionStream instances.

**Additional context**
none

**Comment by vanitasvitae** [comment]
This heavily reminds me of https://github.com/bcgit/bc-java/issues/1379 where BC signatures were not thread safe.
When encrypting / signing a message, the keys that are used to do so are validated in order to determine the expiration date, acceptable algorithms etc.
It might just be the same bug you are hitting here. I'll investigate :)

**Comment by eitch** [comment]
Oh yes, definitely!
