### ISSUE TITLE
PGPainless.getPolicy().setSignatureHashAlgorithmPolicy not available anymore

### ISSUE THREAD

**Issue by jonasjeeliasson** [vanitasvitae/pgpainless#448]
**Describe the bug**
We integrate with an old system that uses SHA-1 still, before version 1.7 we could overwrite the policy like this:

```
PGPainless.getPolicy().setSignatureHashAlgorithmPolicy(
    Policy.HashAlgorithmPolicy.static2022RevocationSignatureHashAlgorithmPolicy()
);
```

**Version**
- `pgpainless-core:1.7.1`
- `pgpainless-sop:1.7.1`

**To Reproduce**
Bump from v1.6 to v1.7 and the setter is not available anymore. Was never deprecated or anything with a reference for how to solve it in another way. We tried to replace it with:

```
PGPainless.getPolicy().setCertificationSignatureHashAlgorithmPolicy(
    Policy.HashAlgorithmPolicy.static2022RevocationSignatureHashAlgorithmPolicy()
);
PGPainless.getPolicy().setDataSignatureHashAlgorithmPolicy(
    Policy.HashAlgorithmPolicy.static2022RevocationSignatureHashAlgorithmPolicy()
);
```

But it can't verify the same signature that worked with the earlier version, we get the following error:

```
sop.exception.SOPGPException$NoSignature: No verifiable signature found.

	at org.pgpainless.sop.InlineVerifyImpl$data$1.writeTo(InlineVerifyImpl.kt:51)
	at org.pgpainless.sop.InlineVerifyImpl$data$1.writeTo(InlineVerifyImpl.kt:31)
	at sop.ReadyWithResult.toByteArrayAndResult(ReadyWithResult.kt:38)
```

**Expected behavior**
We needs to be able to override the hash algorithm on the policy to support SHA-1 signatures.

**Comment by vanitasvitae** [comment]
You are right, there hasn't been any guidance on how to deal with that sudden API change, sorry about that!
Basically, `signatureHashAlgorithmPolicy` has been split up into `certificationSignatureHashAlgorithmPolicy` for all signatures on keys (self-signatures, binding signatures...) and into `dataSignatureHashAlgorithmPolicy` for signatures over data (binary, text).

In the same commit (de9a16125218d8404aaa8e44563026b7ad407499) I also introduced a `smartCertificationSignatureHashAlgorithmPolicy()` factory method, which returns a hash algorithm policy that takes into account not only the hash algorithm itself, but also the date on which the signature was generated. That way, SHA-1 would for example be accepted, if the signature was generated before 2023-02-01 00:00:00 UTC, which deals with a lot of legacy keys out there. Those keys would keep "functioning", although new signatures created with SHA-1 would still be rejected (SHA-1 really should not be used anymore!).

Your attempt of adapting to the API change looks solid in my eyes. The `static2022RevocationSignatureHashAlgorithmPolicy` allows SHA1, regardless of signature creation time, so it *should* work.

In order to dig deeper into the issue I need some more information:
* In what places is SHA-1 being used? Only the data signature itself, or also on self-signatures of the signing key?
* When were those keys and signatures (self-signatures on the key + data signature you are trying to verify) being created?

Ideally, could you provide a test key of similar form which can be used to reproduce the issue?
If not, could you provide a (pseudonymized if you feel more comfortable with that) dump of the public key structure (e.g. by passing the public key through Sequoia-PGP's packet dumper locally `cat public-key.asc | sq toolbox packet dump` or through the web app https://dump.sequoia-pgp.org, *redacting sensitive information like user-ids values, key-ids/fingerprints manually*?

Alternatively, could you replace the SOP verification logic with PGPainless itself, to see what the debug output of PGPainless is?
```java
// Adjust policy
PGPainless.getPolicy().setCertificationSignatureHashAlgorithmPolicy(
    Policy.HashAlgorithmPolicy.static2022RevocationSignatureHashAlgorithmPolicy()
);
PGPainless.getPolicy().setDataSignatureHashAlgorithmPolicy(
    Policy.HashAlgorithmPolicy.static2022RevocationSignatureHashAlgorithmPolicy()
);

ConsumerOptions options = ConsumerOptions.get().addVerificationCert(publicKey);
// e.g. PGPPublicKeyRing publicKey = PGPainless.readKeyRing().publicKeyRing(certBytes);

InputStream signedDataIn = ...; // the signed message
ByteArrayOutputStream bOut = new ByteArrayOutputStream(); // the message content will end up here

DecryptionStream verifier = PGPainless.decryptAndOrVerify().onInputStream(signedDataIn).withOptions(options);
Streams.pipeAll(verifier, bOut);
verifier.close();

MessageMetadata metadata = verifier.getMetadata();
assertTrue(metadata.isVerifiedSigned());
```

**Comment by vanitasvitae** [comment]
I did some testing, generating a key with only SHA1 signatures, and I'm not able to reproduce this issue.
Therefore my guess would be that something else is wrong with the key and 1.7's stricter checks are hitting on that.

E.g. 1.7 now rejects signatures made by primary keys that do not carry the SIGN_DATA keyflag on its self-signature.

Edit: Here is a [test](https://github.com/pgpainless/pgpainless/commit/d966349032cdee9d46fc511dd62b70d8eec25a69) I wrote which could not reproduce the issue.

**Comment by jonasjeeliasson** [comment]
Thanks for looking into this. I will try the things you posted above and see how it plays out.

This is our full usage of painless:

```
@Component
public class PgpService {

    private final SOP sop;

    public PgpService() {
        PGPainless.getPolicy().setCertificationSignatureHashAlgorithmPolicy(
            Policy.HashAlgorithmPolicy.static2022RevocationSignatureHashAlgorithmPolicy()
        );
        PGPainless.getPolicy().setDataSignatureHashAlgorithmPolicy(
            Policy.HashAlgorithmPolicy.static2022RevocationSignatureHashAlgorithmPolicy()
        );

        this.sop = new SOPImpl();
    }

    @SneakyThrows
    public byte[] verify(byte[] payload, String publicKey) {
        var data = sop.inlineVerify()
            .cert(publicKey.getBytes(StandardCharsets.UTF_8))
            .data(payload);
        return data.toByteArrayAndResult().getBytes();
    }

    @SneakyThrows
    public byte[] sign(byte[] payload, String privateKey, String passphrase) {
        return sop.inlineSign()
            .mode(InlineSignAs.text) // or 'Binary'
            .key(privateKey.getBytes(StandardCharsets.UTF_8))
            .withKeyPassword(passphrase)
            .data(payload)
            .getBytes();
    }
}
```

And we have a few IT tests which fails on the verify logic with the exception above. The sign test works tho. I'll see if I can fix some testdata and keys which I can share to reproduce the error. 

The actual data and keys are from our third party and we have tried to get them to improve their security  and not use SHA-1 without success 😅

**Comment by jonasjeeliasson** [comment]
> E.g. 1.7 now rejects signatures made by primary keys that do not carry the SIGN_DATA keyflag on its self-signature.

How can I verify if this is the issue?
