### ISSUE TITLE
java.lang.NullPointerException at org.pgpainless.key.info.KeyAccessor$ViaKeyId.getSignatureWithPreferences(KeyAccessor.kt:74)

### ISSUE THREAD

**Issue by lucy-meachem** [vanitasvitae/pgpainless#457]
**Describe the bug**
When trying to encrypt with a public key made by https://pgptool.org/, which is missing key flags, it null pointers trying to work out the algorithm to use.

**Version**

- `pgpainless-core`: 1.7.2

**To Reproduce**

```
        final var pub = """
                -----BEGIN PGP PUBLIC KEY BLOCK-----
                Version: Keybase OpenPGP v2.0.76
                Comment: https://keybase.io/crypto
                                
                xo0EZzNNhgEEAJ1reakdid2P6u3CVnw0QYRxzFTOWFE6qFhakWPfI2qqTZtym0ro
                /cGtYoUEIJine7FwE3ZBcShHd2jUrK1a2hjEm8JygUw+pa6EaApgdvzYjKleI+Hd
                61cBSmGXf7vxVJE8JwdmFA+IOlbHSInbPT9lIpt1WJFdmNRCKHrhsBsfABEBAAHN
                FGZhcnQgPGZhcnRAZmFydC5jb20+wroEEwEKACQFAmczTYYCGy8DCwkHAxUKCAIe
                AQIXgAMWAgECGQEFCQAAAAAACgkQDF2sS+6wXxf7BwP9ElBivI7Dd26NHA85aLKP
                3NJS0//v45rjZqyDW32krvE4DwFZjkrVn9E7ZuaIWXlL55JYrUXNMnieRDLalIhr
                qnyQrIz88x/xXd1mYZtrSZ2xt5vKx/c6PJA3utxHBGXA9Q5ceLcAb/NUVWo7FYdf
                YwsWtf00l1cFbA75HFB/XibOjQRnM02GAQQAyuoX+NV7nU4rRWXyad1cTcJgu+eS
                F4TstQBCLV3vmgopw2A2lvrWcDSWXHu6GwrwBS56NH6+WIw0ghVVu2beAcageb/x
                WjZw6TOOnTr53sZXcpVG/yKP4+e1Hkg3rGxkCgYkdEXWadJ4YANI1FL/wvS2BPe6
                djeSZ+co8XVZN6EAEQEAAcLAgwQYAQoADwUCZzNNhgUJAAAAAAIbLgCoCRAMXaxL
                7rBfF50gBBkBCgAGBQJnM02GAAoJEFY4U5tMZnCNUWwD/11w7ji1p1udCjavrbUb
                rmJevk5dIqiRQM3zLD4f6AU0fAYWsQR60RoKC5iQoBw4xMLtacNj+lquMSnm6lSa
                B6StiqAmUAiaHwN+TG1+q7EW+EEzfBCFEOmaaBrC3a2sL9wdDTijBzAnSPMh+B8Y
                Vr9tmpgGTU4SuICCttLier9cF3oEAIoIDSY7NyhUBD/9w9TMhoAinnQkJW/xtA/n
                ML2VnOMuv2e1Zj6ddNYwfngWfbQfVdnL4ZnyO0JgiAsMEtyLliBm+TanHxaGS9Tu
                mVcGlmvSbqryo8cCl55aFtrVq0DmsooPfcMAWHn+J0G2XHsA5aQWKZNkZmP1yqVG
                ohhs5iZozo0EZzNNhgEEANvjNOBENOya7QzKog2jG6tbLG0IFTN2wMXVvWNqlFr7
                pKFdpUsg4anR1Y897+zqgqA76QR7Qs4LC6rPWk9WNPnwRrhPGPcAY/kmF+2hIX7l
                PhPNhfO5R/1mMXk16ghjB//cUSKfjwW/IsHVtVa1bl8mESIo8tlCGJRmkp/TYcjT
                ABEBAAHCwIMEGAEKAA8FAmczTYYFCQAAAAACGy4AqAkQDF2sS+6wXxedIAQZAQoA
                BgUCZzNNhgAKCRDhTKlIjdDoMyn3BADFb7+IWQ7eRGIHq9XvizvuNqjF3jGIihA7
                cA7G2UgsuADnXfKlWhBWVqhqB4gnbE8JTLVSBX1oqehrBgifqkFITAiIV4N0j3Se
                jAr2Ul4jFo/o4Arx+iC/y2zhGnGDY43IwCRypJOGjxQXEwINcNFqv8GRMZAJuy8Q
                XW4yGMtLEnXeA/9YJfTOi8jqflvP4A9rmGP2QC7vnCYKJ+OAsrOMTcZES9YqMBoX
                5Yx+uXj5Ryji+sJCP1ZWxJwy/gBhtJe4ginCDqL0IJauotdu5Zjxt8q/lQy4Jd6X
                54slT8ExyJWqRNDkhdqxocjUTkgSR3ttqJUT8BNErt4xbU1TA4glA5ThzA==
                =yxhR
                -----END PGP PUBLIC KEY BLOCK-----
                """;

            final var key = PGPainless.readKeyRing().publicKeyRing(publicKey);

            final var os = new ByteArrayOutputStream();
            final var encryptionStream = PGPainless.encryptAndOrSign()
                    .onOutputStream(os)
                    .withOptions(ProducerOptions.encrypt(new EncryptionOptions()
                                    .setAllowEncryptionWithMissingKeyFlags()
                                    .addRecipient(key)));
```

**Expected behavior**
It shouldn't NPE.

**Additional context**
```
java.lang.NullPointerException
	at org.pgpainless.key.info.KeyAccessor$ViaKeyId.getSignatureWithPreferences(KeyAccessor.kt:74)
	at org.pgpainless.key.info.KeyAccessor.getPreferredSymmetricKeyAlgorithms(KeyAccessor.kt:32)
	at org.pgpainless.encryption_signing.EncryptionBuilder$Companion.negotiateSymmetricEncryptionAlgorithm(EncryptionBuilder.kt:50)
	at org.pgpainless.encryption_signing.EncryptionStream.prepareEncryption(EncryptionStream.kt:86)
	at org.pgpainless.encryption_signing.EncryptionStream.<init>(EncryptionStream.kt:55)
	at org.pgpainless.encryption_signing.EncryptionBuilder$WithOptionsImpl.withOptions(EncryptionBuilder.kt:30)
```

**Comment by vanitasvitae** [comment]
The error happens not because any missing key flags (all binding signatures carry key flags), but because the key is using RSA 1024, which is considered too weak by PGPainless.

I highly recommend you generate a proper key using a proper key generator (the key you provided also doesn't seem to split up responsibilities between subkeys very well, all subkeys are usable for encryption, signing and authentication) if you want to use it for anything serious.

Alternatively (and I highly recommend to do so only as last resort), you can teach PGPainless to accept weak RSA keys by adjusting the public key algorithm policy:
```kotlin
        PGPainless.getPolicy().publicKeyAlgorithmPolicy = Policy.PublicKeyAlgorithmPolicy(
                buildMap {
                        put(PublicKeyAlgorithm.RSA_GENERAL, 1024)  // <--
                        put(PublicKeyAlgorithm.RSA_SIGN, 1024)     // <--
                        put(PublicKeyAlgorithm.RSA_ENCRYPT, 1024)  // <--
                        put(PublicKeyAlgorithm.ELGAMAL_ENCRYPT, 2000)
                        put(PublicKeyAlgorithm.ELGAMAL_GENERAL, 2000)
                        put(PublicKeyAlgorithm.DSA, 2000)
                        put(PublicKeyAlgorithm.ECDSA, 250)
                        put(PublicKeyAlgorithm.EDDSA_LEGACY, 250)
                        put(PublicKeyAlgorithm.DIFFIE_HELLMAN, 2000)
                        put(PublicKeyAlgorithm.ECDH, 250)
                    })
        )
```

**Comment by lucy-meachem** [comment]
do you not think that a more specific exception should be thrown here? a npe isn't a very intuitive way of saying that your key is too weak.

**Comment by vanitasvitae** [comment]
Yeah, the current situation is not ideal and certificate evaluation is complex. I'm currently working on a high-level certificate evaluator implementation in Bouncy Castle, which will learn from the mistakes made in PGPainless.
For the mean time I can create a patch that catches this particular edge case though :)

**Comment by lucy-meachem** [comment]
it's not dreadfully important, ofc, but the key as above is what you get when you click on the first link when you google "pgp generator", for testing purposes - making an otherwise extremely easy to use library quite a bit more problematic
